### ISSUE TITLE
hotbuild settings tab and UI crash

### ISSUE THREAD

**Issue by cascadianmetapod** [pietervanh/hotbuild2#33]
After trying to set hotbuild to the community default of arrows, my game crashed, and afterwards the hotbuild tab in settings would not load. Upon opening settings, the screen flashes aswell. My hotbuild settings from just before the crash remain, despite the mod being repeatedly uninstalled/reinstalled, and disabling the mod in PAMM seems to have no effect. I believe it is an issue with the arrow community default setting, and that deleting this off from wherever on the computer user mod settings are stored may solve the issue. I've ruled out mod conflicts.

**Comment by pietervanh** [comment]
Probably fixed already
